on:
  push:
    branches: ["main"]
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt update && sudo apt install -y nodejs golang && snap install -y trivy
      - name: build backend
        run: echo "foo"
      - name: build frontend
        run: cd frontend;npm ci;npx ng build
      - name: deploy
        run: echo "foo"
